spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: EUR,USD,INR

email:
  host: smtp://gmail.com
  port: 7000

payment-gateway: paypal